#!/usr/bin/env bash
site="http://www.ceve-market.org"
wget -O db.7z $site$(curl $site/api/ 2>/dev/null|grep excel|cut -d '"' -f2)
db_file_tmp=$(7z l db.7z |grep xls|awk '{print $NF}')
7z e db.7z
db_file=eve_db.xls
mv $db_file_tmp $db_file
